/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nvidiav1 "github.com/k8s-gpushare/gpushare-crd-controller/pkg/apis/nvidia/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGPUResources implements GPUResourceInterface
type FakeGPUResources struct {
	Fake *FakeNvidiaV1
	ns   string
}

var gpuresourcesResource = schema.GroupVersionResource{Group: "nvidia.segma.tech", Version: "v1", Resource: "gpuresources"}

var gpuresourcesKind = schema.GroupVersionKind{Group: "nvidia.segma.tech", Version: "v1", Kind: "GPUResource"}

// Get takes name of the gPUResource, and returns the corresponding gPUResource object, and an error if there is any.
func (c *FakeGPUResources) Get(ctx context.Context, name string, options v1.GetOptions) (result *nvidiav1.GPUResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gpuresourcesResource, c.ns, name), &nvidiav1.GPUResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUResource), err
}

// List takes label and field selectors, and returns the list of GPUResources that match those selectors.
func (c *FakeGPUResources) List(ctx context.Context, opts v1.ListOptions) (result *nvidiav1.GPUResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gpuresourcesResource, gpuresourcesKind, c.ns, opts), &nvidiav1.GPUResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nvidiav1.GPUResourceList{ListMeta: obj.(*nvidiav1.GPUResourceList).ListMeta}
	for _, item := range obj.(*nvidiav1.GPUResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gPUResources.
func (c *FakeGPUResources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gpuresourcesResource, c.ns, opts))

}

// Create takes the representation of a gPUResource and creates it.  Returns the server's representation of the gPUResource, and an error, if there is any.
func (c *FakeGPUResources) Create(ctx context.Context, gPUResource *nvidiav1.GPUResource, opts v1.CreateOptions) (result *nvidiav1.GPUResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gpuresourcesResource, c.ns, gPUResource), &nvidiav1.GPUResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUResource), err
}

// Update takes the representation of a gPUResource and updates it. Returns the server's representation of the gPUResource, and an error, if there is any.
func (c *FakeGPUResources) Update(ctx context.Context, gPUResource *nvidiav1.GPUResource, opts v1.UpdateOptions) (result *nvidiav1.GPUResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gpuresourcesResource, c.ns, gPUResource), &nvidiav1.GPUResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUResource), err
}

// Delete takes name of the gPUResource and deletes it. Returns an error if one occurs.
func (c *FakeGPUResources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(gpuresourcesResource, c.ns, name), &nvidiav1.GPUResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGPUResources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gpuresourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nvidiav1.GPUResourceList{})
	return err
}

// Patch applies the patch and returns the patched gPUResource.
func (c *FakeGPUResources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1.GPUResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpuresourcesResource, c.ns, name, pt, data, subresources...), &nvidiav1.GPUResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUResource), err
}
