/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nvidiav1 "github.com/k8s-gpushare/gpushare-crd-controller/pkg/apis/nvidia/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGPUNodeInfos implements GPUNodeInfoInterface
type FakeGPUNodeInfos struct {
	Fake *FakeNvidiaV1
	ns   string
}

var GPUNodeInfosResource = schema.GroupVersionResource{Group: "nvidia.segma.tech", Version: "v1", Resource: "GPUNodeInfos"}

var GPUNodeInfosKind = schema.GroupVersionKind{Group: "nvidia.segma.tech", Version: "v1", Kind: "GPUNodeInfo"}

// Get takes name of the GPUNodeInfo, and returns the corresponding GPUNodeInfo object, and an error if there is any.
func (c *FakeGPUNodeInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *nvidiav1.GPUNodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(GPUNodeInfosResource, c.ns, name), &nvidiav1.GPUNodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUNodeInfo), err
}

// List takes label and field selectors, and returns the list of GPUNodeInfos that match those selectors.
func (c *FakeGPUNodeInfos) List(ctx context.Context, opts v1.ListOptions) (result *nvidiav1.GPUNodeInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(GPUNodeInfosResource, GPUNodeInfosKind, c.ns, opts), &nvidiav1.GPUNodeInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nvidiav1.GPUNodeInfoList{ListMeta: obj.(*nvidiav1.GPUNodeInfoList).ListMeta}
	for _, item := range obj.(*nvidiav1.GPUNodeInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested GPUNodeInfos.
func (c *FakeGPUNodeInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(GPUNodeInfosResource, c.ns, opts))

}

// Create takes the representation of a GPUNodeInfo and creates it.  Returns the server's representation of the GPUNodeInfo, and an error, if there is any.
func (c *FakeGPUNodeInfos) Create(ctx context.Context, GPUNodeInfo *nvidiav1.GPUNodeInfo, opts v1.CreateOptions) (result *nvidiav1.GPUNodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(GPUNodeInfosResource, c.ns, GPUNodeInfo), &nvidiav1.GPUNodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUNodeInfo), err
}

// Update takes the representation of a GPUNodeInfo and updates it. Returns the server's representation of the GPUNodeInfo, and an error, if there is any.
func (c *FakeGPUNodeInfos) Update(ctx context.Context, GPUNodeInfo *nvidiav1.GPUNodeInfo, opts v1.UpdateOptions) (result *nvidiav1.GPUNodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(GPUNodeInfosResource, c.ns, GPUNodeInfo), &nvidiav1.GPUNodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUNodeInfo), err
}

// Delete takes name of the GPUNodeInfo and deletes it. Returns an error if one occurs.
func (c *FakeGPUNodeInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(GPUNodeInfosResource, c.ns, name), &nvidiav1.GPUNodeInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGPUNodeInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(GPUNodeInfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nvidiav1.GPUNodeInfoList{})
	return err
}

// Patch applies the patch and returns the patched GPUNodeInfo.
func (c *FakeGPUNodeInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1.GPUNodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(GPUNodeInfosResource, c.ns, name, pt, data, subresources...), &nvidiav1.GPUNodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GPUNodeInfo), err
}
